---
title: "Iteration"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
library(httr)

knitr::opts_chunk$set(
	fig.width = 6, 
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis" 
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```


## z-score function

```{r}

#if not use function:

x_vec = rnorm(30, mean=5, sd=3)

(x_vec - mean(x_vec)) / sd(x_vec)
```

```{r}

z_scores = function(x) {
  
  z = (x - mean(x)) / sd(x)
  return(z)
  
}

z_scores(x_vec)
```

## try some inputs

```{r}
z_scores(3)
z_scores("my name is jeff")
z_scores(iris)
z_scores(sample(c(TRUE, FALSE), 25, replace = TRUE))
```


## Weird above. Add some validation rules on the input
```{r}

z_scores = function(x) {
  
  z = (x - mean(x)) / sd(x)
  return(z)
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } 
  
   if (length(x) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  
  
}

z_scores(x_vec)
```


##multiple outcomes
```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } 
  
  if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}


mean_and_sd(x_vec)
```
## multiple inpouts

```{r}
sim_mean_sd = function(sampl_size, mu = 2, sigma = 3) {
  
  sim_data = tibble(
    x = rnorm(n = sampl_size, mean = mu, sd = sigma),
  )
  
  sim_data %>% 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}

sim_mean_sd(10000, 7, 2)
sim_mean_sd(sampl_size = 1000, mu = 3, sigma = 5)

##positional matching V.S. naming matching
```


```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

        review_titles = 
          dynamite_html %>%
          html_nodes(".review-title") %>%
          html_text() 
        
        review_stars = 
          dynamite_html %>%
          html_nodes(".review-rating") %>%
          html_text() %>%
          str_extract("^\\d") %>%
          as.numeric()
        
        review_text = 
          dynamite_html %>%
          html_nodes(".review-text-content span") %>%
          html_text() %>% 
          str_replace_all("\n", "") %>% 
          str_trim()
        
        reviews = tibble(
          title = review_titles,
          stars = review_stars,
          text = review_text
        )
```



